# _config.yml

title: Brieux Kaczmarczyk
description: |
  Welcome to my portfolio !  
  I recently graduated from UCLouvain with a degree in physics. Since then, I've followed a Data Science & Statistics formation through both UCLouvain and additional coursework.  
  I consider myself an AI & Data enthusiast, and I am currently looking for a position related to these topics !

  The following projects were (successfully !) achieved during my education at UCLouvain.

# Enable the Slate theme
theme: jekyll-theme-slate

# GitHub Pages settings (optional, but useful)
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social media and contact (optional)
author:
  name: Brieux Kaczmarczyk
  email: kaczbrieux@gmail.com
  github: BrieuxK
  linkedin: Brieux Kaczmarczyk

# Other customization (optional)
show_downloads: false  # You can turn this on if you want a "Download" link
